development:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 2
